### ISSUE TITLE
ERC20

### ISSUE THREAD

**Issue by Yash9276** [bansaltushar014/Chapter-Solidity#3]
<h1>ERC20</h1>
<p>I want to contribute by adding ERC20 token demo  , please assign it to me  :)
</p>

**Comment by bansaltushar014** [comment]
Sure @Yash9276 , Please go ahead. Let us know if there is any help required.

**Comment by Yash9276** [comment]
I want to contribute to this project under Hacktoberfest guidelines so please add Hacktoberfest tag to this issue

**Comment by bansaltushar014** [comment]
Done.

**Comment by bansaltushar014** [comment]
Hello @Yash9276 , Is there any help required?

**Comment by BChainbuddy** [comment]
I would like to add the ERC20 contract if the role is still open?

**Comment by bansaltushar014** [comment]
Hi @Yash9276 , Are you still working on it? If not, please inform then I will assign it to @BChainbuddy

**Comment by bansaltushar014** [comment]
Hi @BChainbuddy , Are you interested to take this task?

**Comment by BChainbuddy** [comment]
Yes, I would gladly do it.

**Comment by bansaltushar014** [comment]
Sure @BChainbuddy .
