### ISSUE TITLE
Demo for ERC-173: Contract Ownership Standard

### ISSUE THREAD

**Issue by bansaltushar014** [bansaltushar014/Chapter-Solidity#6]
Create a simple demo for ERC-173

* Do your research and have an understanding
* Write simple and easiest logic to cover the basics of ERC-173
* Create the PR which contains the code
* [Optional] Also include the published article's link into the Readme of ERC-173

Refer to below links to start

https://eips.ethereum.org/EIPS/eip-173

**Comment by hparihar-07** [comment]
I can work on this assign this to me

**Comment by bansaltushar014** [comment]
Sure @hparihar-07 , I have assigned you the task. Feel free to reach out if you face any issue.

**Comment by hparihar-07** [comment]
@bansaltushar014  bro check the PR☺️
