### ISSUE TITLE
Demo for ERC1271 - Standard Signature Validation Method

### ISSUE THREAD

**Issue by Hares27** [bansaltushar014/Chapter-Solidity#9]
ERC 1271 - Externally Owned Accounts (EOA) can sign messages with their associated private keys, but currently contracts cannot. It propose a standard way for any contracts to verify whether a signature on a behalf of a given contract is valid. This is possible via the implementation of a isValidSignature(hash, signature) function on the signing contract, which can be called to validate a signature.

Resources to follow: 
1. https://eips.ethereum.org/EIPS/eip-1271
2. https://docs.cow.fi/tutorials/how-to-place-erc-1271-smart-contract-orders/the-basics-of-erc-1271
3. https://www.youtube.com/watch?v=sc1x_du6UXk&ab_channel=EthereumCatHerders

**Comment by bansaltushar014** [comment]
Hi @Hares27 , Please review the above changes. I was expecting something like this. Please add more resources if there is any.

**Comment by Hares27** [comment]
Hello @bansaltushar014 , I followed the official implementation of ERC1271.The resources you provided are also give more clarity on this.
